#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
VENV_DIR="$HOME/.local/share/agent-box/venv"
PROJECT_DIR="$(cd "$(dirname "$0")" && pwd)"
XBAR_PLUGIN_DIR=""

echo ""
echo "🤖 Agent Box - xbar Installation"
echo "===================================="
echo ""

# Function to print colored output
print_status() {
    echo -e "${BLUE}→${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC}  $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Step 1: Check for Ollama
print_status "Checking for Ollama..."
if ! command -v ollama &> /dev/null; then
    print_warning "Ollama not found. Install it with:"
    echo "  brew install ollama"
    echo ""
    read -p "Continue without Ollama? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
else
    print_success "Ollama found"
    
    # Check if Ollama is running
    if ! curl -sf http://localhost:11434/api/tags >/dev/null 2>&1; then
        print_warning "Ollama is not running"
        echo "  Start it with: ollama serve"
        echo "  Or it will start automatically when needed"
    else
        print_success "Ollama is running"
    fi
fi

# Step 2: Check for xbar
print_status "Checking for xbar..."
if [ ! -d "/Applications/xbar.app" ]; then
    print_error "xbar not found!"
    echo ""
    echo "Please install xbar:"
    echo "  1. Download from: https://xbarapp.com/"
    echo "  2. Or: brew install --cask xbar"
    echo "  3. Open xbar and configure plugin directory"
    echo "  4. Run this script again"
    echo ""
    exit 1
fi
print_success "xbar found"

# Step 3: Find xbar plugin directory
print_status "Finding xbar plugin directory..."

# Try common locations
POSSIBLE_DIRS=(
    "$HOME/Library/Application Support/xbar/plugins"
    "$HOME/.xbar"
    "$HOME/xbar-plugins"
)

for dir in "${POSSIBLE_DIRS[@]}"; do
    if [ -d "$dir" ]; then
        XBAR_PLUGIN_DIR="$dir"
        break
    fi
done

# If not found, ask user
if [ -z "$XBAR_PLUGIN_DIR" ]; then
    print_warning "Could not auto-detect xbar plugin directory"
    echo ""
    echo "Please find your xbar plugin directory:"
    echo "  1. Click xbar icon in menu bar"
    echo "  2. Click 'Preferences' → 'Plugin Folder...'"
    echo "  3. Note the path shown"
    echo ""
    read -p "Enter xbar plugin directory path: " XBAR_PLUGIN_DIR
    
    if [ ! -d "$XBAR_PLUGIN_DIR" ]; then
        print_error "Directory not found: $XBAR_PLUGIN_DIR"
        exit 1
    fi
fi

print_success "Plugin directory: $XBAR_PLUGIN_DIR"

# Step 4: Create virtual environment
print_status "Creating isolated Python virtual environment..."

if [ -d "$VENV_DIR" ]; then
    print_warning "Virtual environment already exists at $VENV_DIR"
    read -p "Remove and recreate? (y/N): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$VENV_DIR"
    fi
fi

if [ ! -d "$VENV_DIR" ]; then
    mkdir -p "$(dirname "$VENV_DIR")"
    python3 -m venv "$VENV_DIR"
    print_success "Virtual environment created"
else
    print_success "Using existing virtual environment"
fi

# Step 5: Install agb in the virtual environment
print_status "Installing agb CLI in virtual environment..."

cd "$PROJECT_DIR/agb"

# Upgrade pip first
"$VENV_DIR/bin/pip" install --upgrade pip --quiet

# Install in editable mode so changes auto-apply
"$VENV_DIR/bin/pip" install -e . --quiet

cd "$PROJECT_DIR"

print_success "agb CLI installed (editable mode)"

# Verify installation
if "$VENV_DIR/bin/agb" --version &>/dev/null; then
    VERSION=$("$VENV_DIR/bin/agb" --version 2>&1)
    print_success "Verified: $VERSION"
else
    print_error "agb installation verification failed"
    exit 1
fi

# Step 6: Install xbar plugin
print_status "Installing xbar plugin..."

PLUGIN_SOURCE="$PROJECT_DIR/xbar/agb.5m.sh"
PLUGIN_DEST="$XBAR_PLUGIN_DIR/agb.5m.sh"

# Create symlink (so updates to repo affect plugin)
if [ -L "$PLUGIN_DEST" ] || [ -f "$PLUGIN_DEST" ]; then
    rm -f "$PLUGIN_DEST"
fi

ln -s "$PLUGIN_SOURCE" "$PLUGIN_DEST"
chmod +x "$PLUGIN_SOURCE"

print_success "Plugin symlinked: $PLUGIN_DEST"

# Step 7: Update plugin with correct paths
print_status "Configuring plugin paths..."

# Create a local config that doesn't get committed
cat > "$PROJECT_DIR/xbar/.config.local" << EOF
# Auto-generated by install-xbar.sh
VENV_PATH="$VENV_DIR"
AGB_PATH="$VENV_DIR/bin/agb"
PROJECT_DIR="$PROJECT_DIR"
EOF

print_success "Plugin configured"

# Step 8: Refresh xbar
print_status "Refreshing xbar..."

# Try to refresh xbar via its URL scheme
if command -v open &> /dev/null; then
    open "xbar://app.xbarapp.com/refreshAllPlugins" 2>/dev/null || true
    sleep 1
fi

print_success "xbar refreshed"

# Final summary
echo ""
echo "╔════════════════════════════════════════════════╗"
echo "║                                                ║"
echo "║  ✅  Installation Complete!                    ║"
echo "║                                                ║"
echo "╚════════════════════════════════════════════════╝"
echo ""
echo "📍 Installation Details:"
echo "   • Virtual env: $VENV_DIR"
echo "   • CLI binary: $VENV_DIR/bin/agb"
echo "   • xbar plugin: $PLUGIN_DEST"
echo "   • Development: $PROJECT_DIR"
echo ""
echo "🚀 Next Steps:"
echo ""
echo "   1. Look for 🤖 icon in your menu bar"
echo "   2. If not visible, click xbar → 'Refresh All'"
echo "   3. Copy some text (Cmd+C)"
echo "   4. Click 🤖 → 'Fix Grammar' or 'Rewrite Text'"
echo "   5. Wait for notification, then paste (Cmd+V)"
echo ""
echo "💡 Tips:"
echo ""
echo "   • Development changes auto-apply (editable install)"
echo "   • Update plugin: git pull && ./install-xbar.sh"
echo "   • View logs: tail -f ~/.local/state/ab/logs/agent-box.log"
echo "   • Uninstall: rm -rf $VENV_DIR && rm $PLUGIN_DEST"
echo ""
echo "🔍 Troubleshooting:"
echo ""
echo "   • No 🤖 icon: Open xbar app, click 'Refresh All'"
echo "   • ⚠️ icon: Start Ollama with 'ollama serve'"
echo "   • Commands fail: Check logs or run 'agb text fix' in terminal"
echo ""
print_success "Happy automating! 🎉"
echo ""
