"""Review generator for synthesizing feedback into GitHub reviews."""

import subprocess
from pathlib import Path
from typing import Optional
from datetime import datetime

from pr_agent.models.feedback import FeedbackCollection, FeedbackSeverity
from pr_agent.models.pr import PRMetadata


class ReviewGenerator:
    """Generates GitHub review comments from collected feedback."""
    
    def __init__(self, pr_metadata: PRMetadata, feedback: FeedbackCollection):
        """Initialize the review generator.
        
        Args:
            pr_metadata: PR metadata
            feedback: Collection of feedback items
        """
        self.pr_metadata = pr_metadata
        self.feedback = feedback
    
    def generate_review_body(self, include_summary: bool = True) -> str:
        """Generate the main review comment body.
        
        Args:
            include_summary: Whether to include a summary at the top
            
        Returns:
            Formatted markdown review body
        """
        parts = []
        
        if include_summary:
            parts.append(self._generate_summary())
            parts.append("")
        
        # Add feedback items grouped by file
        parts.append(self._format_feedback_by_file())
        
        # Add footer
        parts.append("")
        parts.append("---")
        parts.append(f"*Generated by PR Review Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}*")
        
        return "\n".join(parts)
    
    def _generate_summary(self) -> str:
        """Generate a summary section for the review.
        
        Returns:
            Formatted summary markdown
        """
        if not self.feedback.items:
            return "## Summary\n\nNo issues found. Code looks good! ✓"
        
        counts = self.feedback.count_by_severity()
        total = len(self.feedback.items)
        
        # Determine overall assessment
        if counts[FeedbackSeverity.CRITICAL] > 0:
            assessment = "⚠️ **Critical issues found** - Please address before merging"
        elif counts[FeedbackSeverity.IMPORTANT] > 0:
            assessment = "⚡ **Important issues found** - Should be addressed"
        else:
            assessment = "💡 **Minor suggestions** - Consider these improvements"
        
        summary_parts = [
            "## Review Summary",
            "",
            assessment,
            "",
            f"**Total feedback items**: {total}",
            f"- 🔴 Critical: {counts[FeedbackSeverity.CRITICAL]}",
            f"- 🟡 Important: {counts[FeedbackSeverity.IMPORTANT]}",
            f"- 💡 Suggestions: {counts[FeedbackSeverity.SUGGESTION]}",
            f"- ❓ Questions: {counts[FeedbackSeverity.QUESTION]}",
        ]
        
        return "\n".join(summary_parts)
    
    def _format_feedback_by_file(self) -> str:
        """Format feedback items grouped by file.
        
        Returns:
            Formatted markdown with feedback grouped by file
        """
        if not self.feedback.items:
            return ""
        
        # Group feedback by file
        files_feedback = {}
        for item in self.feedback.items:
            if item.file not in files_feedback:
                files_feedback[item.file] = []
            files_feedback[item.file].append(item)
        
        parts = ["## Detailed Feedback", ""]
        
        # Sort files alphabetically
        for file_path in sorted(files_feedback.keys()):
            items = files_feedback[file_path]
            
            parts.append(f"### `{file_path}`")
            parts.append("")
            
            # Sort items by line number if available
            items_sorted = sorted(
                items,
                key=lambda x: int(x.lines.split('-')[0]) if x.lines and x.lines[0].isdigit() else 0
            )
            
            for item in items_sorted:
                parts.append(item.format_for_github())
                parts.append("")
        
        return "\n".join(parts)
    
    def generate_inline_comments(self) -> list[dict]:
        """Generate inline comments for specific lines.
        
        Returns:
            List of inline comment data structures for gh CLI
        """
        inline_comments = []
        
        for item in self.feedback.items:
            # Only create inline comments for items with line numbers
            if not item.lines:
                continue
            
            # Parse line range
            if '-' in item.lines:
                start_line, end_line = item.lines.split('-')
                start_line = int(start_line)
                end_line = int(end_line)
            else:
                start_line = end_line = int(item.lines)
            
            comment_data = {
                'path': item.file,
                'line': end_line,  # GitHub uses the end line for the comment
                'body': item.comment,
                'severity': item.severity.value
            }
            
            inline_comments.append(comment_data)
        
        return inline_comments
    
    def generate_review_decision(self) -> str:
        """Determine the review decision based on feedback severity.
        
        Returns:
            Review decision: 'APPROVE', 'REQUEST_CHANGES', or 'COMMENT'
        """
        if not self.feedback.items:
            return 'APPROVE'
        
        counts = self.feedback.count_by_severity()
        
        # Request changes if there are critical issues
        if counts[FeedbackSeverity.CRITICAL] > 0:
            return 'REQUEST_CHANGES'
        
        # Request changes if there are multiple important issues
        if counts[FeedbackSeverity.IMPORTANT] >= 3:
            return 'REQUEST_CHANGES'
        
        # Otherwise just comment
        return 'COMMENT'
    
    def save_review_draft(self, output_path: Path) -> None:
        """Save the review draft to a file.
        
        Args:
            output_path: Path to save the review draft
        """
        review_body = self.generate_review_body()
        output_path.write_text(review_body)
    
    def preview_review(self) -> str:
        """Generate a preview of the review for display.
        
        Returns:
            Formatted preview text
        """
        decision = self.generate_review_decision()
        body = self.generate_review_body()
        
        decision_label = {
            'APPROVE': '✅ APPROVE',
            'REQUEST_CHANGES': '❌ REQUEST CHANGES',
            'COMMENT': '💬 COMMENT'
        }
        
        parts = [
            "=" * 80,
            f"REVIEW PREVIEW - Decision: {decision_label.get(decision, decision)}",
            "=" * 80,
            "",
            body,
            "",
            "=" * 80,
        ]
        
        return "\n".join(parts)


class ReviewImprover:
    """Uses Copilot to improve review wording and suggestions."""
    
    def __init__(self, copilot_client):
        """Initialize the review improver.
        
        Args:
            copilot_client: Copilot client instance
        """
        self.client = copilot_client
    
    async def improve_feedback_wording(self, feedback_text: str) -> str:
        """Improve the wording of feedback text using Copilot.
        
        Args:
            feedback_text: Original feedback text
            
        Returns:
            Improved feedback text
        """
        prompt = f"""Please improve the following code review feedback to make it more constructive, clear, and actionable:

Original feedback:
{feedback_text}

Improved feedback:"""
        
        # Use Copilot to generate improved wording
        response = await self.client.chat(
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert at providing constructive code review feedback. "
                               "Make feedback clear, specific, and actionable while maintaining a respectful tone."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.7
        )
        
        return response.choices[0].message.content.strip()
    
    async def generate_suggested_fix(self, file_content: str, issue_description: str) -> Optional[str]:
        """Generate a suggested code fix for an issue.
        
        Args:
            file_content: Content of the file with the issue
            issue_description: Description of the issue
            
        Returns:
            Suggested fix code, or None if not applicable
        """
        prompt = f"""Given the following code and issue, suggest a specific code fix:

Code:
```
{file_content}
```

Issue:
{issue_description}

Suggested fix:"""
        
        response = await self.client.chat(
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert code reviewer. Provide specific, working code fixes."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.3  # Lower temperature for more deterministic code
        )
        
        return response.choices[0].message.content.strip()
    
    async def enhance_review(self, review_body: str, pr_context: str) -> str:
        """Enhance the entire review with better structure and clarity.
        
        Args:
            review_body: Original review body
            pr_context: Context about the PR
            
        Returns:
            Enhanced review body
        """
        prompt = f"""Enhance this code review to make it more comprehensive and helpful:

PR Context:
{pr_context}

Current Review:
{review_body}

Enhanced Review:"""
        
        response = await self.client.chat(
            messages=[
                {
                    "role": "system",
                    "content": "You are an expert code reviewer. Enhance reviews with better structure, "
                               "clarity, and actionable insights while maintaining all the original feedback."
                },
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            temperature=0.7
        )
        
        return response.choices[0].message.content.strip()


class GitHubReviewPoster:
    """Posts reviews to GitHub using gh CLI."""
    
    def __init__(self, pr_number: int, owner: str, repo: str):
        """Initialize the GitHub review poster.
        
        Args:
            pr_number: PR number
            owner: Repository owner
            repo: Repository name
        """
        self.pr_number = pr_number
        self.owner = owner
        self.repo = repo
    
    def post_review(
        self,
        review_body: str,
        action: str = 'COMMENT',
        inline_comments: Optional[list[dict]] = None
    ) -> tuple[bool, str]:
        """Post a review to GitHub.
        
        Args:
            review_body: The main review comment body
            action: Review action - 'APPROVE', 'REQUEST_CHANGES', or 'COMMENT'
            inline_comments: Optional list of inline comments
            
        Returns:
            Tuple of (success, message)
        """
        # Map action to gh CLI flag
        action_flags = {
            'APPROVE': '--approve',
            'REQUEST_CHANGES': '--request-changes',
            'COMMENT': '--comment'
        }
        
        action_flag = action_flags.get(action.upper(), '--comment')
        
        # Build gh pr review command
        cmd = [
            'gh', 'pr', 'review', str(self.pr_number),
            action_flag,
            '--body', review_body
        ]
        
        # TODO: Add inline comments support when gh CLI supports it better
        # Currently gh CLI has limited support for inline comments via command line
        
        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                check=True
            )
            
            return True, f"Review posted successfully! {result.stdout.strip()}"
            
        except subprocess.CalledProcessError as e:
            error_msg = e.stderr.strip() if e.stderr else str(e)
            return False, f"Failed to post review: {error_msg}"
    
    def check_gh_authenticated(self) -> tuple[bool, str]:
        """Check if gh CLI is authenticated.
        
        Returns:
            Tuple of (is_authenticated, message)
        """
        try:
            result = subprocess.run(
                ['gh', 'auth', 'status'],
                capture_output=True,
                text=True,
                check=False
            )
            
            if result.returncode == 0:
                return True, "GitHub CLI is authenticated"
            else:
                return False, "GitHub CLI is not authenticated. Run: gh auth login"
                
        except FileNotFoundError:
            return False, "GitHub CLI (gh) is not installed"
    
    def get_pr_review_url(self) -> str:
        """Get the URL to the PR reviews.
        
        Returns:
            URL string
        """
        return f"https://github.com/{self.owner}/{self.repo}/pull/{self.pr_number}#reviews"
